baseURL = "https://priyapennathur.netlify.app/"
languageCode = "en-us"
title = "Priya Pennathur"
name = "Priya Pennathur"
pluralizelisttitles = false
theme = "hughey-lab-theme"

[[menu.main]]
    name = "Research"
    identifier = "research"
    url = "/research/"
    weight = 1
[[menu.main]]
    name = "Publications"
    identifier = "papers"
    url = "/papers/"
    weight = 2

[[menu.main]]
    name = "News"
    identifier = "news"
    url = "/news/"
    weight = 3
[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog/"
    weight = 4
