baseURL = "https://pennathurlab.netlify.app/"
languageCode = "en-us"
title = "Pennathur Lab"
name = "Pennathur Lab"
pluralizelisttitles = false
theme = "hughey-lab-theme"

[[menu.main]]
    name = "Papers"
    identifier = "papers"
    url = "/papers/"
    weight = 4
[[menu.main]]
    name = "Software"
    identifier = "software"
    url = "/software/"
    weight = 3
[[menu.main]]
    name = "People"
    identifier = "people"
    url = "/people/"
    weight = 2
[[menu.main]]
    name = "News"
    identifier = "news"
    url = "/news/"
    weight = 1

